restaurant_ordering_pos_management_system/restaurant_ordering_pos_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ropms import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ropms.urls')),
    path('admin/pos/dashboard', views.admin_pos_dashboard, name="admin_pos_dashboard"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant_ordering_pos_management_system/ropms/urls.py
from django.urls import path
from ropms import views

app_name = "ropms"

urlpatterns = [
    path('', views.index_client, name="index_client"),
    path('registration/', views.registration, name="registration"),
    path('table-selection/', views.table_selection, name="table_selection"),
    path('cancel-table-selection/delete/<int:id>/', views.cancel_table_selection, name="cancel_table_selection"),
    path('menu-selection/<int:id>/', views.menu_selection, name="menu_selection"),
    path('table-selection/menu-selection/menu-detail/<int:id>/<int:tid>/', views.menu_detail, name="menu_detail"),
    path('table-selection/menu-selection/cart/<int:id>/<int:tid>/', views.cart, name="cart"),
    path('table-selection/menu-selection/cart/add-to-cart/<int:id>/<int:mid>/', views.add_item_to_cart, name="add_item_to_cart"),
    path('table-selection/menu-selection/cart/update-to-cart/<int:mid>/', views.update_item_to_cart, name="update_item_to_cart"),
    path('table-selection/menu-selection/cart/delete-from-cart/<int:cid>/', views.delete_item_from_the_cart, name="delete_item_from_the_cart"),
    path('checkout/', views.checkout, name="checkout"),


    
]

restaurant_ordering_pos_management_system/ropms/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Customer(models.Model):

    GENDER_LIST = (
        ('Male','Male'),
        ('Female', 'Female'),
    )

    email = models.EmailField(max_length=100, unique=True, null=True)
    f_name = models.CharField(max_length=100)
    m_name = models.CharField(max_length=100)
    l_name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=100, choices=GENDER_LIST, default=GENDER_LIST[0][0])
    is_valid = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True) 
    
    def __str__(self):
        return f'{self.l_name} {self.f_name} {self.m_name}'

class CustomerTable(models.Model):

    STATUS_LIST = (
        ('Occupied','Occupied'),
        ('Unoccupied', 'Unoccupied'),
    )

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250) 
    capacity = models.IntegerField()
    status = models.CharField(max_length=250, choices=STATUS_LIST, default=STATUS_LIST[1][0])  
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ropms:menu_selection', args=[self.id])

class Menu(models.Model):

    CATEGORY_LIST = (
        ('Beverages', 'Beverages'),
        ('Break Fast', 'Break Fast'),
        ('Desserts', 'Desserts'),
        ('Vegetables', 'Vegetables'),
        ('Soup', 'Soup'),
        ('Salad', 'Salad'),
        ('Main Course', 'Main Course'),
    )

    STATUS_LIST = (
        ('Available','Available'),
        ('Unavailable', 'Unavailable'),
    )
    
    image = models.FileField(upload_to="images/")
    name = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=50, choices=STATUS_LIST, default=STATUS_LIST[0][0])
    category = models.CharField(max_length=50, choices=CATEGORY_LIST, default=CATEGORY_LIST[0][0])
    price = models.DecimalField(max_digits=5, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.name
    
    # def get_absolute_url(self):
    #     return reverse("ropms:menu_detail", args=[self.id])

class Waiting(models.Model):
    customer = models.OneToOneField(Customer, related_name="customer", on_delete=models.CASCADE)
    table = models.OneToOneField(CustomerTable, related_name="table", on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return str(self.customer)

class Cart(models.Model):
    customer = models.ForeignKey(Customer, related_name="cart_fk_customer", on_delete=models.CASCADE)
    menu_item = models.ForeignKey(Menu, related_name="cart_fk_menu_item", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0) 
    date_added = models.DateTimeField(auto_now_add=True) 
 
    def __str__(self):
        return str(self.menu_item)

class POS(models.Model):
    customer_name = models.CharField(max_length=100)
    table_name = models.CharField(max_length=100)
    menu_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2, default="0")
    quantity = models.IntegerField()
    total = models.DecimalField(max_digits=10, decimal_places=2) 
    date_added = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return self.menu_name

restaurant_ordering_pos_management_system/ropms/forms.py
from django import forms
from ropms import models

class CustomerForm(forms.ModelForm):  
    class Meta:
        model = models.Customer
        exclude = ("date_added",)

restaurant_ordering_pos_management_system/ropms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy 
from django.db.models import Q, Avg, Count, Sum, F, FloatField
from django.db import IntegrityError
from django.contrib import messages
from ropms import models, forms
from functools import wraps

from django.contrib.auth.decorators import login_required 
import json
# Create your views here.

# Decorator
def email_required(function):
    @wraps(function)
    def wrap(request, *args, **kwargs):
        try:
            email = models.Customer.objects.all().get(Q(email=request.session.get('customer_email', False)) & Q(is_valid=True)) 

            kwargs['email'] = email
        except models.Customer.DoesNotExist:
            return HttpResponseRedirect(reverse("ropms:index_client"))
        return function(request,  *args, **kwargs) 
    return wrap

# Main Views 
def index_client(request):
    template_name = "client/index.html"  
    if request.method == 'POST':
        email_address = request.POST.get("email") 
        try:
            email = models.Customer.objects.all().get(Q(email=email_address)) 
            if email.is_valid:
                request.session['customer_email'] = email.email 
                request.session.set_expiry(600)
                return  HttpResponseRedirect(reverse("ropms:table_selection"))
            else:
                messages.warning(request, "You account is under aprroval! please wait.")
        except models.Customer.DoesNotExist:
            messages.error(request,  "Your email has not been registered!" )
    context = {  
    }

    return render(request, template_name, context)


def registration(request):
    template_name = "client/registration.html"

    if request.method == 'GET':
        form = forms.CustomerForm(request.GET or None)
    elif request.method == 'POST':
        form = forms.CustomerForm(request.POST or None)
        if form.is_valid():
            form.save() 
            return HttpResponseRedirect(reverse("ropms:index_client"))
    context = {
        'form': form,
    }

    return render(request, template_name, context)


@email_required
def table_selection(request, *args, **kwargs): 
    template_name = "client/table-selection.html"
    if request.method == 'GET':   
        tables = models.CustomerTable.objects.all() 
        context = { 
            'tables': tables,
        }

    return render(request, template_name, context)


@email_required
def menu_selection(request, *args, **kwargs):
    template_name = "client/menu-selection.html"
    table = get_object_or_404(models.CustomerTable, id=kwargs.get('id', None))  
    email = kwargs.get('email', None)
    menu_list = models.Menu.objects.all().filter(Q(status='Available'))

    search_term = request.GET.get('search')
    if search_term:
        menu_list = menu_list.filter(Q(name__icontains=search_term) | Q(category__icontains=search_term))
    
    try:
        waiting = models.Waiting.objects.all().get(Q(table=table))
        if  waiting.customer == email:
            
            context = { 
                'waiting': waiting,
                'menu_list': menu_list,
            }
            return render(request, template_name, context)
        else:
            
            messages.error(request, "This table is already occupied by another customer")
            return HttpResponseRedirect(reverse("ropms:table_selection"))
    except models.Waiting.DoesNotExist:
        try:
            waiting = models.Waiting.objects.create(customer=email, table=table)
            table.status = 'Occupied'
            table.save() 
            context = {
                'waiting': waiting,
                'menu_list': menu_list,
            }
            return render(request, template_name, context)
        except IntegrityError:
            messages.error(request, "This table is already occupied by another customer or you are still been assigned on a different table. Please make sure to cancel your table selection first before transfering to a different table.")
            return HttpResponseRedirect(reverse("ropms:table_selection")) 


@email_required
def cancel_table_selection(request, *args, **kwargs): 
    waiting = get_object_or_404(models.Waiting, id=kwargs.get('id', None)) 
    table = get_object_or_404(models.CustomerTable, id=waiting.table.id)
    table.status = "Unoccupied"
    table.save()
    waiting.delete()
    messages.success(request, "You had been successfully canceled your table selection. You may now select a new table!")
    return HttpResponseRedirect(reverse("ropms:table_selection"))

@email_required
def menu_detail(request, *args, **kwargs):
    template_name = "client/menu-detail.html" 
    table = get_object_or_404(models.CustomerTable, id=kwargs.get('tid', None))  
    menu = get_object_or_404(models.Menu, Q(status='Available'), id=kwargs.get('id', None)) 
    related_menu = models.Menu.objects.all().filter(Q(category=menu.category)).exclude(Q(id=menu.id)) 

  
    context = {
        'menu': menu,
        'related_menu': related_menu,
        'table': table,
        'customer': kwargs.get('email',None),
    }
    return render(request, template_name, context)

@email_required
def cart(request, *args, **kwargs):
    # https://docs.djangoproject.com/en/3.1/topics/db/aggregation/ 
    template_name = "client/cart.html" 
    # id = kwargs.get('id',None)
    cid = kwargs.get('email', None)
    tid = kwargs.get('tid',None)
    waiting = get_object_or_404(models.Waiting, customer__id=cid.id, table__id=tid)
    cart = models.Cart.objects.all().filter(Q(customer__id=cid.id)).order_by('-id')

    total_quantity = cart.aggregate(total=Sum('quantity'))['total'] 
    total_quantity = total_quantity if total_quantity != None else 0 
    total_amount = cart.aggregate(total=Sum(F('quantity') * F('menu_item__price'), output_field=FloatField()))['total'] 
    total_amount = total_amount if total_amount != None else 0  
 
    context = {
        'waiting': waiting,
        'cart': cart, 
        'total_quantity': total_quantity,
        'total_amount': float(total_amount),
    }
    return render(request, template_name, context)

@email_required
def add_item_to_cart(request, *args, **kwargs):
    data = dict() 
    if request.is_ajax():
        if request.method == 'POST':
            customer = get_object_or_404(models.Customer, id=kwargs.get('email',None).id)
            menu_item = get_object_or_404(models.Menu, id=kwargs.get('mid', None))

            json_request = request.body
            json_request= json.loads(json_request)
            quantity = json_request['quantity'] 
            # cart, not_created = models.Cart.objects.get_or_create(customer=customer, menu_item=menu_item,  defaults={
            #     'quantity': quantity,
            # }) 
            cart, not_created = models.Cart.objects.get_or_create(customer=customer, menu_item=menu_item) 
            # cart.quantity += int(quantity)
            cart.quantity = F('quantity') + quantity
            cart.save()
            # cart, not_created = models.Cart.objects.update_or_create(customer=customer, menu_item=menu_item, defaults={
            #     'quantity': 2,
            # }) 

            total_all_quantity, total_all_amount, cart = get_results(customer) 

            data['context'] = { 
                'total_all_quantity': total_all_quantity,
                'total_all_amount': total_all_amount,
            }
        return JsonResponse(data)
    else:
        raise Http404()

@email_required
def update_item_to_cart(request, *args, **kwargs):
    data = dict()
    customer = get_object_or_404(models.Customer, id=kwargs.get('email',None).id)
    menu_item = get_object_or_404(models.Menu, id=kwargs.get('mid', None))
    if request.is_ajax():
        if request.method == 'POST':
            json_response = request.body
            json_response = json.loads(json_response)
            quantity = json_response['quantity']
            cart_item, not_created = models.Cart.objects.update_or_create(customer=customer, menu_item=menu_item, defaults={
                'quantity': quantity,
            })  
            total_amount = cart_item.quantity * cart_item.menu_item.price 

            total_all_quantity, total_all_amount, cart = get_results(customer) 
             
            data['context'] = {
                'total_amount': total_amount,
                'total_all_quantity': total_all_quantity,
                'total_all_amount': total_all_amount,
            }
        return JsonResponse(data)
    else:
        raise Http404()
    
@email_required
def delete_item_from_the_cart(request, *args, **kwargs):
    data = dict()
 
    if request.is_ajax():
        if request.method == 'POST':
            customer = get_object_or_404(models.Customer, id=kwargs.get('email',None).id)
            cart = get_object_or_404(models.Cart, id=kwargs.get('cid', None))
            
            cart.delete()

            total_all_quantity, total_all_amount, cart = get_results(customer) 
             
            data['context'] = { 
                'total_all_quantity': total_all_quantity,
                'total_all_amount': total_all_amount,
                'count': cart.count(),
            }
            return JsonResponse(data)
    else:
        raise Http404()

def get_results(customer):

    cart = models.Cart.objects.all().filter(Q(customer=customer)).order_by('-id')
    total_all_quantity = cart.aggregate(total=Sum('quantity'))['total'] 
    total_all_quantity = total_all_quantity if total_all_quantity != None else 0
    total_all_amount = cart.aggregate(total=Sum(F('quantity') * F('menu_item__price'), output_field=FloatField()))['total'] 
    total_all_amount = total_all_amount if total_all_amount != None else 0

    return total_all_quantity, float(total_all_amount), cart


@email_required

restaurant_ordering_pos_management_system/ropms/templates/client/cart.html
{% extends 'client/base.html' %}
{% load static %}
{% load custom_template_tags %}

{% block title %}
RALF Modern Cuisine Restaurant Cart
{% endblock title %}

{% block css %}
<style>
    table th, tr, td {
        text-align: center !important;
    }
</style>
{% endblock css %}

{% block nav_shopping_cart %}
<a class="active" href="{% url 'ropms:cart' waiting.customer.id waiting.table.id %}" id="nav-shopping-cart-summary">
    {% nav_shopping_cart request.session.customer_email %}
</a>
{% endblock nav_shopping_cart %}

{% block nav_search_form %}
{% endblock nav_search_form%}

{% block content %}
<div class="well well-small">
    <h1>Check Out <small class="pull-right" id="total-items"> {{cart.count}} Items are in the cart </small></h1>
    <hr class="soften">

    <table class="table table-bordered table-condensed" id="table-cart" border="1" style="text-align: center;">
        <thead>
            <tr>
                <th style="width: 20%;">Picture</th>
                <th style="width: 10%;">Name</th>
                <th style="width: 30%;">Description</th>
                <th style="width: 10%;">Unit price</th>
                <th style="width: 20%;">Qty </th>
                <th style="width: 10%;">Total</th>
            </tr>
        </thead>
        <tbody>
            {% for c in cart %}
            <tr>
                <td><img width="100" src="{{ c.menu_item.image.url }}" alt="Not Available"></td>
                <td>{{ c.menu_item.name }}</td>
                <td>{{ c.menu_item.description }}</td>
                <td>₱ {{ c.menu_item.price }}</td>
                <td>
                    <input class="span1 item-quantity" style="max-width:34px" placeholder="1" size="16" type="text"
                        value="{{ c.quantity }}" readonly>
                    <div class="input-append">
                        <button class="btn btn-mini delete-value" type="button"
                            data-url="{% url 'ropms:update_item_to_cart' c.menu_item.id %}">-</button>
                        <button class="btn btn-mini add-value" type="button"
                            data-url="{% url 'ropms:update_item_to_cart' c.menu_item.id %}">+</button>
                        <button class="btn btn-mini btn-danger delete-all-menu-items" type="button"
                            data-url="{% url 'ropms:delete_item_from_the_cart' c.id %}"><span
                                class="icon-remove"></span></button>
                    </div>
                </td>
                <td class="total-amount">₱ {% total_amount c.quantity c.menu_item.price %}</td>
            </tr>
            {% endfor %}

        </tbody>
        <tfoot>
            <tr>
                <th colspan="5" class="alignR">Total Quantity: </th>
                <th id="total-all-quantity">{{total_quantity}}</th>
            </tr>
            <tr>
                <th colspan="5" class="alignR">Total Cost: </th>
                <th class="label label-primary" id="total-all-amount"> ₱ {{total_amount}}</th>
            </tr>
            <tr>
                <th colspan="5" class="alignR">Payment: </th>
                <th class="label label-primary" id="cash"> ₱ </th>
            </tr>
            <tr>
                <th colspan="5" class="alignR">Change: </th>
                <th class="label label-primary" id="change"> ₱ </th>
            </tr>
        </tfoot>
    </table><br>


    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>
                    <form id="form-payment" class="form-inline" method="POST" data-url="{% url 'ropms:checkout' %}">
                        {% csrf_token %}
                        <div class="controls">
                            <label style="min-width:159px"> PAYMENT: </label>
                            <input id="payment" type="number" class="input-medium" placeholder="AMOUNT" required
                                min="1">
                            <span class="help-inline" style="display: none;" id="error-message">Please correct the
                                error</span>
                            <button type="submit" class="shopBtn"> CONFIRM</button>
                        </div>

                    </form>
                </td>
            </tr>

        </tbody>
    </table>

    <a href="{% url 'ropms:menu_selection' waiting.table.id %}" class="shopBtn btn-large"><span
            class="icon-arrow-left"></span> Continue Menu Selection
    </a>
    <!-- <a id="printReceipt" class="shopBtn btn-large pull-right">Print to complete<span class="icon-arrow-right"></span></a> -->

</div>

{% endblock content%}

restaurant_ordering_pos_management_system/ropms/templates/client/index.html
{% extends 'client/base.html' %}
{% load static %}

{% block title %}
RALF Modern Cuisine Restaurant Table Selection
{% endblock title %}

{% block css %}
{% endblock css %}


{% block nav_home %}
<a class="active" href="{% url 'ropms:index_client' %}"> <span class="icon-home"></span> Home</a>
{% endblock nav_home %}

{% block nav_shopping_cart %}
{% endblock nav_shopping_cart %}

{% block icon_shopping_cart %}
{% endblock icon_shopping_cart %}

{% block nav_index %}
<li class="active"><a href="{% url 'ropms:index_client' %}">Home</a></li>
{% endblock nav_index %}

{% block nav_search_form %}
{% endblock nav_search_form%}

{% block content %}


<div class="well">
    <form class="form-horizontal" method="POST">
        {% csrf_token %}
        <h3>Enter Email Address If You Are Already Registered</h3> 
        {% include 'partials/_messages.html' %}
        <div class="control-group">
            <label class="control-label" for="inputEmail">Email <sup>*</sup></label>
            <div class="controls">
                <input type="email" placeholder="Email" name="email" required>
            </div>
        </div>
       
 
        <div class="control-group">
            <div class="controls">
                <input type="submit" name="submitAccount" value="Enter" class="exclusive shopBtn">
                <input type="button" value="Register" class="exclusive shopBtn" onclick="window.location.href='{% url 'ropms:registration' %}'"> 
            </div>
        </div>
    </form>
</div>

{% endblock content%}

restaurant_ordering_pos_management_system/ropms/templates/client/menu-detail.html
{% extends 'client/base.html' %}
{% load static %}
{% load custom_template_tags %}

{% block title %}
RALF Modern Cuisine Restaurant Menu Details
{% endblock title %}



{% block nav_shopping_cart %}
<a href="{% url 'ropms:cart' customer.id table.id %}" id="nav-shopping-cart-summary">
    {% nav_shopping_cart request.session.customer_email %}
</a>
{% endblock nav_shopping_cart %}


{% block menu_list %}
<li class="active"><a href="">Menu List</a></li>
{% endblock menu_list %}

{% block nav_search_form %} 
{% endblock nav_search_form%}
{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'ropms:menu_selection' table.id %}">Back</a> <span class="divider">/</span></li> 
    <li class="active">Preview {{waiting}}</li>
</ul>
<div class="well well-small">
    <div class="row-fluid">
        <div class="span5">
            <div id="myCarousel" class="carousel slide cntr">
                <div class="carousel-inner">
                    <div class="item next left">
                        <a href="#"> <img src="{{ menu.image.url }}" alt="Not Available" style="width:100%"></a>
                    </div>
                    <div class="item">
                        <a href="#"> <img src="{{ menu.image.url }}" alt="Not Available" style="width:100%"></a>
                    </div>
                    <div class="item active left">
                        <a href="#"> <img src="{{ menu.image.url }}" alt="Not Available" style="width:100%"></a>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            </div>
        </div>
        <div class="span7">
            <h3>{{ menu.name }} [₱{{ menu.price }}]</h3>
            <hr class="soft">

            <form class="form-horizontal qtyFrm">
                <div class="control-group">
                    <label class="control-label"><span>₱{{ menu.price }}</span></label>
                    <div class="controls">
                        <input id="menu_item_quantity" type="number" class="span6" placeholder="Qty." min="1" value="1" required>
                    </div>
                </div> 
                <h4>{{ menu.category }}</h4>
                <p> {{ menu.description }} </p>
                <p> 
                    <a href="{% url 'ropms:add_item_to_cart' customer.id menu.id %}" class="shopBtn add-to-cart"><span class=" icon-shopping-cart"></span> Add to cart</a> 
                </p>
            </form>
        </div>
    </div>
    <hr class="softn clr">


    <ul id="productDetail" class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">Product Details</a></li>
        <li class=""><a href="#profile" data-toggle="tab">Related Products </a></li>

    </ul>
    <div id="myTabContent" class="tab-content tabWrapper">
        <div class="tab-pane fade active in" id="home">
            <h4>Product Information</h4>
            <table class="table table-striped">
                <tbody>
                    <tr class="techSpecRow">
                        <td class="techSpecTD1">Status:</td>
                        <td class="techSpecTD2">{{ menu.status }}</td>
                    </tr>
                    <tr class="techSpecRow">
                        <td class="techSpecTD1">Date Added:</td>
                        <td class="techSpecTD2">{{ menu.date_added }}</td>
                    </tr>
                </tbody>
            </table>
            <p>{{ menu.description }}</p>

        </div>
        <div class="tab-pane fade" id="profile">
            {% for r_menu in related_menu %}
            <div class="row-fluid">
                <div class="span2">
                    <img src="{{ r_menu.image.url }}" alt="Not Available">
                </div>
                <div class="span6">
                    <h5>{{ r_menu.name }}</h5>
                    <p>
                        {{ r_menu.description }}
                    </p>
                </div>
                <div class="span4 alignR">
                    <form class="form-horizontal qtyFrm">
                        <h3> ₱{{ r_menu.price }}</h3>
                        <label class="checkbox">
                           {{ r_menu.category }}
                        </label><br>
                        <div class="btn-group">
                            <a href="{% url 'ropms:add_item_to_cart' customer.id r_menu.id %}" class="defaultBtn add-to-cart"><span class=" icon-shopping-cart"></span> Add to cart</a>
                                Add to cart</a>
                            <a href="{% url 'ropms:menu_detail' r_menu.id table.id %}" class="shopBtn">VIEW</a>
                          
                        </div>
                    </form>
                </div>
            </div>
            {% if not forloop.last %}<hr class="soft">{% endif %} 
            {% endfor %}
        </div>
       
    </div>

</div>
{% endblock content%}

restaurant_ordering_pos_management_system/ropms/templates/client/menu-selection.html
{% extends 'client/base.html' %}
{% load static %}
{% load custom_template_tags %}


{% block title %}
RALF Modern Cuisine Restaurant Menu Selection
{% endblock title %}


{% block nav_shopping_cart %}
<a href="{% url 'ropms:cart' waiting.customer.id waiting.table.id %}" id="nav-shopping-cart-summary">
    {% nav_shopping_cart request.session.customer_email %}
</a> 
{% endblock nav_shopping_cart %}

{% block menu_list %}
<li class="active"><a href="">Menu List</a></li>
{% endblock menu_list %}

{% block nav_search_form %}
<form method="GET" class="navbar-search pull-right" style="margin-right: 5px;">
    <input type="text" name="search" placeholder="Search" class="search-query span2" value="{{request.GET.search}}">
</form>
{% endblock nav_search_form%}

{% block content %}
<div class="well well-small">
    {% for menu in menu_list %}
    <div class="row-fluid">
        <div class="span2">
            <img src="{{ menu.image.url }}" alt="No Image Available">
        </div>
        <div class="span6">

            <h5>{{ menu.name }}</h5>
            <p>
                {{ menu.description }}
            </p>
        </div>
        <div class="span4 alignR">
            <form class="form-horizontal qtyFrm">
                <h3> ₱{{ menu.price }}</h3>
                <label class="checkbox">
                   {{menu.category}}
                </label><br>
                <div class="btn-group">
                    <a href="{% url 'ropms:add_item_to_cart' waiting.customer.id menu.id %}" class="defaultBtn add-to-cart"><span class=" icon-shopping-cart"></span> Add to cart</a>
                    <a href="{% url 'ropms:menu_detail' menu.id waiting.table.id %}" class="shopBtn">VIEW</a>
                </div>
            </form>
        </div>
    </div>
    {% if not forloop.last %}<hr class="soften">{% endif %} 
    {% endfor %} 
</div>
<div class="well"> 
    <a href="{% url 'ropms:cancel_table_selection' waiting.id %}" class="shopBtn exclusive">Cancel</a>
</div>

{% endblock content%}

restaurant_ordering_pos_management_system/ropms/templates/client/nav_shopping_cart.html
 
    <span class="icon-shopping-cart"></span> 
    {{total_quantity}} Item(s)
    - <span class="badge badge-warning"> ₱{{total_amount}}</span> 

restaurant_ordering_pos_management_system/ropms/templates/client/table-selection.html
{% extends 'client/base.html' %}
{% load static %}

{% block title %}
RALF Modern Cuisine Restaurant Table Selection
{% endblock title %}

{% block css %}
<style>
    .span4{
        margin: 2px !important;
    }  
</style>
{% endblock css %}

 
{% block nav_shopping_cart %}
{% endblock nav_shopping_cart %}

{% block icon_shopping_cart %}
{% endblock icon_shopping_cart %}

{% block nav_table_selection %}
<li class="active"><a href="{% url 'ropms:table_selection' %}">Table Selection </a></li>
{% endblock nav_table_selection %}

{% block nav_search_form %}
{% endblock nav_search_form%}

{% block content %}
<h3>Our Tables </h3>
{% include 'partials/_messages.html' %}
<div class="row-fluid">
    <ul class="thumbnails"> 
      {% for t in tables %}
      <li class="span4">
        <div class="thumbnail">
          <a href="" class="overlay"></a> 
          <a href=""><img src="{% static 'assets/food_img/table.jpg' %}" alt=""></a>
          <div class="caption cntr">
              <p>{{ t.name }}</p> 
              {% if t.status == 'Occupied' %} 
              <p style="color: red;"><strong>{{ t.status }}</strong></p> 
              {% else %}
              <p><strong>{{ t.status }}</strong></p> 
              {% endif %} 
              <h4><a class="shopBtn" href="{{ t.get_absolute_url }}" title="select table" readonly> Select </a></h4> 
              <div class="actionList">
                  <a class="pull-left" href="">Capacity: {{ t.capacity }}</a> 
                  <a class="pull-left" href=""> {{ t.description }}</a> 
              </div> 
              <br class="clr"> 
              
          </div>
        </div>
      </li>
      {% endfor%} 
    </ul>
  </div>
{% endblock content%} 